version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:3306'
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    ports:
      - '${REDIS_PORT}:6379'
volumes:
  mysql:
